### ISSUE TITLE
Build with Fortran support

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/openmpi-feedstock#1]
@astrofrog are you interested in trying that? I do not have time right now but I will certainly try this at some point.

**Comment by astrofrog** [comment]
I tried to do this locally and it looks like the OpenMPI install ignores the ``DYLD_FALLBACK_LIBRARY_PATH`` environment variable: https://github.com/open-mpi/ompi/issues/2068

**Comment by ocefpaf** [comment]
Done in #2
