### ISSUE TITLE
openmpi compiled with clang for OSX

### ISSUE THREAD

**Issue by bebatut** [conda-forge/openmpi-feedstock#12]
Hi,

It looks like `openmpi` for OSX was compiled with clang and not gcc (as I thought from the recipe of the package):

```
$ mpic++ --show
clang++ -I/Users/bebatut/miniconda3/envs/openmpi/include -Wl,-rpath,/Users/bebatut/miniconda3/envs/openmpi/lib -L/Users/bebatut/miniconda3/envs/openmpi/lib -lmpi_cxx -lmpi
```

I remarked that when I used your package as dependencies for a Bioconda package. I was trying to compile this tool and I got this error:

```
mpic++   -g3 -Wall -c -fmessage-length=0 -fopenmp -Wno-sign-compare  -std=c++11 -O3 -lgomp -MMD -MP -MF"src/main.d" -MT"src/main.o" -o "src/main.o" "../src/main.cpp"
clang: warning: -lgomp: 'linker' input unused
clang: error: unsupported option '-fopenmp'
``` 

Weird as the openmpi package was supposed to use gcc and not clang? 😄 

Is there any way to fix this?
I think we need to force the use of gcc (and not clang) for OSX.

Thanks a lot for your support

Bérénice

**Comment by dalcinl** [comment]
I think we depend on `gcc` just to get Fortran support. As `clang` is the system's compiler, I think it makes sense to build `openmpi` with `clang`, and make the MPI C/C++ compiler wrappers `mpicc`/`mpic++` use `clang`/`clang++` as well.

Please note that if you want to change the backend compiler, you can simply execute `export OMPI_CXX=g++` before using `mpic++`.

**Comment by severous** [comment]
you shoud execute `export OMPI_CXX=g++-your version of g++`
