### ISSUE TITLE
--enable-ipv6 flag for IPv6 only machines

### ISSUE THREAD

**Issue by ChenYuHo** [conda-forge/openmpi-feedstock#165]
### Comment:

I was trying to run some mpi applications on a set of machines with only IPv6 addresses but failed.
It looks like --enable-ipv6 is the missing block.
Are there any concerns regarding --enable-ipv6 flag?

https://github.com/conda-forge/openmpi-feedstock/blob/eb5c1f15d543444292506bc3c6c039aeeae894a1/recipe/build-mpi.sh#L59C1-L59C12

**Comment by dalcinl** [comment]
I don't have any concerns. Unless someone has any, please submit a rebuild PR and I'll happily review and eventually merge it.
