### ISSUE TITLE
Missing openib support

### ISSUE THREAD

**Issue by pllopis** [conda-forge/openmpi-feedstock#38]
It seems that all the builds have the openib btl disabled, which leaves tcp communication as the sole inter-node communication fabric. This is unfortunate as openmpi is commonly used on clusters with low-latency interconnects where RDMA/ibverbs communication is desirable.

It is possible to check the provided communication mechanisms (BTLs in openmpi-speak) by using:
`ompi_info --param btl all`

Which currently lists:
```
                 MCA btl: tcp (MCA v2.1.0, API v3.0.0, Component v3.1.4)
                 MCA btl: vader (MCA v2.1.0, API v3.0.0, Component v3.1.4)
                 MCA btl: self (MCA v2.1.0, API v3.0.0, Component v3.1.4)

```

Notice how tcp is present, but openib is not.

I am not familiar with writing feedstock, but I believe that simply adding a build-time package dependency on libibverbs.so would do the trick, as usually OpenMPI will detect this and automatically build openib.

Would this be possible? Thank you in advance!

**Comment by minrk** [comment]
I think the first step required is to create a conda package for openib. Then openmpi can be built against openib.

**Comment by pllopis** [comment]
That makes sense. However note that openib is just the interface name within OpenMPI and is named like that for legacy reasons. Nowadays the OpenFabrics packages providing the necessary build-time dependencies to have openib support in OpenMPI are usually grouped under a package named rdma-core (in RHEL and Ubuntu-based distros at least).

rdma-core-devel in my system requires: ibacm, libibumad, librdmacm, libibverbs, and rdma-core.

In a local openmpi installation where configure detects support for the openib btl I see the following variables defined:

```
btl_openib_LIBS='-lrdmacm  -libverbs '
btl_openib_CPPFLAGS='  -I/usr/include/infiniband'
```

Let me know if you need any other info.

**Comment by schr476** [comment]
Any update on this?
