### ISSUE TITLE
Openmpi-mpicxx is incompatible with ... something?

### ISSUE THREAD

**Issue by wfspotz** [conda-forge/openmpi-feedstock#44]
Issue: Running `conda install openmpi-mpicxx` results in a confusing incompatibility error:
<details>

```
$ conda install openmpi-mpicxx
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - openmpi-mpicxx


Note that strict channel priority may have removed packages required for satisfiability.
```

</details>

I am starting with a clean environment and the confusing part is that incompatibilities should take two to tango, but only one package was specified.  What is `openmpi-mpicxx` incompatible with?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/williamspotz/anaconda3/envs/clean:
#
# Name                    Version                   Build  Channel
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : clean
    active env location : /Users/williamspotz/anaconda3/envs/clean
            shell level : 2
       user config file : /Users/williamspotz/.condarc
 populated config files : /Users/williamspotz/.condarc
          conda version : 4.7.5
    conda-build version : 3.18.6
         python version : 3.6.7.final.0
       virtual packages :
       base environment : /Users/williamspotz/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/williamspotz/anaconda3/pkgs
                          /Users/williamspotz/.conda/pkgs
       envs directories : /Users/williamspotz/anaconda3/envs
                          /Users/williamspotz/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.6.7 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by ocefpaf** [comment]
Can you try installing it in an env like,

```
conda create --name TEST openmpi-mpicxx
```

?

The existing package you have there may be the culprit of the `incompatibility`.

**Comment by wfspotz** [comment]
Unfortunately, I get the same

**Comment by ocefpaf** [comment]
It works on Linux so it may be a missing package on macOS. I'll try to find a OS X machine to figure this out.

**Comment by minrk** [comment]
This happens with strict channel priority, but not flexible because the compiler package comes from defaults and there doesn't appear to be a compatible libcxx on conda-forge.

I think the defaults channel compilers are incompatible with strict channel priority and conda-forge.

Flexib

**Comment by ocefpaf** [comment]
@isuruf I thought that all the packages on OS X were built with the compilers on `defaults` that did not exist on conda-forge. What is the strategy for `libcxx` on mscOS going forward? Are we going to stop using `defaults` and maintain our compilers?

**Comment by msarahan** [comment]
That's bad.  We need to find a way to keep these compatible.  That answer absolutely should not be "you're stuck with what defaults has" but we should strive to have our packages be compatible with runtimes in either place - either by having the runtime only in defaults, as we do for gcc/gxx, or by ensuring that CF and conda both have compatible runtimes and stay in sync on compiler stack better.

**Comment by wfspotz** [comment]
Let me know if you want to sit down together and use my Mac

**Comment by isuruf** [comment]
@ocefpaf, they are compatible, but clang_osx-64 is asking for libcxx==4.0.1 instead of libcxx>=4.0.1. In conda-forge, we don't have 4.0.1 and therefore strict priority is an issue.

**Comment by wfspotz** [comment]
As a temporary workaround, `channel_priority: flexible` seems to be working for me.

**Comment by ocefpaf** [comment]
> @ocefpaf, they are compatible, but clang_osx-64 is asking for libcxx==4.0.1 instead of libcxx>=4.0.1. In conda-forge, we don't have 4.0.1 and therefore strict priority is an issue.

@isuruf that is an incompatibility IMO. Any packages that we cannot keep up and/or should have a canonical source should not be duplicated in conda-forge. A long time ago we decided that the compilers runtimes would be the like that.

What are the reason for conda-forge to keep the `libcxx` there? Can we removed them?

**Comment by isuruf** [comment]
> Any packages that we cannot keep up and/or should have a canonical source should not be duplicated in conda-forge

We are keeping up with 8.0.1. It's just that defaults isn't keeping up.

**Comment by isuruf** [comment]
> What are the reason for conda-forge to keep the libcxx there?

For newer features than 4.0.1

**Comment by ocefpaf** [comment]
If we have a new one and and things are properly pinned the problem should not exist with `strict` then. Maybe something is not OK with the metadata?

**Comment by isuruf** [comment]
That's not how strict works if I understand correctly. `libcxx==4.0.1` is required but conda looks for `libcxx` in conda-forge only since there's a `libcxx` in conda-forge

**Comment by wfspotz** [comment]
Per #34, I installed `openmpi-mpicxx`, but when I try to compile my code, I get `The Open MPI wrapper compiler was unable to find the specified compiler` error.

**Comment by ocefpaf** [comment]
> That's not how strict works if I understand correctly. `libcxx==4.0.1` is required but conda looks for `libcxx` in conda-forge only since there's a `libcxx` in conda-forge

If it cannot fallback to a pinned package then we need to fix `strict`. The logic of "does not exist on a channel" encompasses a pin. I guess the alternative would be to vendor that version :-(

**Comment by msarahan** [comment]
no, I've hit that hurdle myself.  I also immediately said "oh, I need to adjust strict."  Perhaps for exact versions it can fall through, but for any range of any sort, strict really needs to error out, IMHO.  Otherwise, it's just likely to do dumb things by being too flexible.

I'm not set in stone on this, but we need to think very carefully about use cases and our desired behavior.

**Comment by ocefpaf** [comment]
For now I'm thinking about vendoring 4.0.1 again to avoid issues with `strict`. A long term plan would be fix `strict` to get the right version when it does not exist in a higher priority channel.

Closing this b/c `flexible is a workaround and `strict` will work once we vendor it.

**Comment by minrk** [comment]
btw, https://github.com/conda/conda/pull/8961 is a PR that updates strict channel resolution to use match specs instead of names only. It would fix this case, but currently is more flexible than I think @msarahan would like. I can update it to only apply when exact versions are requested, etc. That PR's coming from the perspective of [repo2docker and frozen environments](https://github.com/jupyter/repo2docker/issues/731)
