### ISSUE TITLE
Discussion on Open MPI failures due to CUDA awareness

### ISSUE THREAD

**Issue by leofang** [conda-forge/openmpi-feedstock#55]
In open-mpi/ompi#7460 we found and reported that the CUDA-aware Open MPI (#54) is causing some mpi4py-fft tests to fail (see also [here](https://bitbucket.org/mpi4py/mpi4py-fft/issues/15/tests-failed-in-test_mpifftpy)). This is suggesting the decision of turning on CUDA awareness may cause issues for downstream ***CPU-only*** projects. I have one question and two proposals to remedy this before Open MPI (or mpi4py-fft?!) fixes the error.

Question for downstream package maintainers: Have you seen or received any bug report after we pushed out #54 recently? 

Proposals on possible fixes:
1. Restore the old `openmpi` package, and rename the current output `openmpi` to `openmpi-cuda`:
  - Pro: for CPU projects `openmpi` is readily usable as before
  - Con: for projects that support different flavors *and* GPU usage, you get one extra flavor to build against
  - Con: for openmpi-feedstock we'd generate one extra package for each supported platform
2. Keep the current recipe as is, but turn off the CUDA awareness by default (via setting `OMPI_MCA_opal_cuda_support=false` as suggested in https://github.com/open-mpi/ompi/issues/7460#issuecomment-590515467):
  - Pro: we have the same pro and avoid the cons above
  - Con: for GPU projects that need CUDA  awareness, the users need to remember setting `OMPI_MCA_opal_cuda_support=true`, but currently the feedstock has no documentation page to communicate this subtlety (plus it's likely users don't even read webpages here)

Tagging @conda-forge/hdf5 @conda-forge/h5py @conda-forge/mpi4py @conda-forge/fftw @conda-forge/dask-mpi. (I can only think of a few projects that support different MPI flavors, so please feel free to tag relevant parties.)

cc: @jakirkham @conda-forge/openmpi @conda-forge/mpi4py-fft for awareness

**Comment by dalcinl** [comment]
@leofang Why don't we rather make CUDA support opt-in rather than opt-out, at least until we can figure out the root of the issue? I mean, we could try to disable CUDA support in the installed MCA config file, then users wanting to use GPUs have to explicitly enable it, either by command line to mpiexec or environment variables?

**Comment by leofang** [comment]
Yes, it’s exactly my proposal 2. I am just worried that users might have no way to know they need to explicitly enable it. 

(AFAIK, Open MPI documentation is poor on the CUDA awareness support. smcuda or these MCAs is never explicitly mentioned.)

**Comment by jakirkham** [comment]
Yeah I think Lisandro's proposal sounds reasonable. Agree there is a question about how we make this visible. Some thoughts (though we are not limited to these). Please let me know if you have others though 🙂

1. Add a post-link script to tell users about this (like [this one]( https://github.com/conda-forge/drmaa-feedstock/blob/464b1dc4fc46fac198b2e027b8a4823ff57c48fa/recipe/post-link.sh ))
2. Provide a README in the recipe here
3. Document in other projects that use this package

**Comment by leofang** [comment]
John, thanks for suggestions! The post-link thing looks interesting -- when is the script invoked? Is it called only once and right after `conda install` is finished, or every time the package is used?

**Comment by beckermr** [comment]
Option 4 - create a metapackage openmpi-cuda that does the correct things to turn this on

**Comment by leofang** [comment]
@beckermr What's the difference between your metapackage and my Proposal 1 (add one more output `openmpi-cuda`)?

**Comment by beckermr** [comment]
Well, we don't have to ship a full library to switch a setting.

**Comment by jakirkham** [comment]
Right was also thinking about that. Thanks for adding that Matt! 😄

Leo, yes, it is called when the package is installed either directly or through the dependency of something.

**Comment by leofang** [comment]
I see, thanks Matt! But the metapackage will have the same cons as I listed for Proposal 1, so while  you don't ship a full `openmpi`, you end up shipping one extra `mpi4py`, `fftw`, `hdf5`, `h5py`, etc. 😂

I think we could adopt **Proposal 2 (implemented like what Lisandro said) + post-link script** as a temporary solution until we find out the root of errors. What do you think?

**Comment by beckermr** [comment]
Sure. Just putting the option out there in case it was useful.

**Comment by leofang** [comment]
One more question for @jakirkham @beckermr: Is it possible for you to find out all downstream packages of `openmpi`? I think it'd be nice to raise awareness for potential issues.

**Comment by beckermr** [comment]
Yes we can get this info. More questions though. How temporary is this situation?

**Comment by leofang** [comment]
Matt, I am not sure what you meant temporary. If we messed up in mpi4py/mpi4py-fft (very unlikely I think), we'll be able to fix it quickly, and resume the CUDA awareness by default. 

If it turns out Open MPI screwed up (which is almost always the case according to Lisandro 🤣), we could have two possibilities:
1. If a hot-fix is provided by Open MPI devs, we can apply the patch here and turn on CUDA awareness.
2. If it needs to wait until v4.0.3/v4.1.0 is out, we will have to disabled it as discussed.

Do I answer your question?

**Comment by beckermr** [comment]
Yes you did!

**Comment by leofang** [comment]
btw, I made a PR #56 based on the above discussion.
