### ISSUE TITLE
Invalid value for opal_cuda_support

### ISSUE THREAD

**Issue by leofang** [conda-forge/openmpi-feedstock#63]
We got a user reporting that when using the `openmpi` package from nsls2forge/openmpi-feedstock (basically a clone of this feedstock) on a system with a GPU installed, the following error was encountered, see https://github.com/NSLS-II/edrixs/issues/96:
```
$ mpirun -n 1 python example_2_AIM_XAS.py
--------------------------------------------------------------------------
An invalid value was supplied for an enum variable.

  Variable     : opal_cuda_support
  Value        : trueid
  Valid values : 0: f|false|disabled|no|n, 1: t|true|enabled|yes|y
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_register_params failed
  --> Returned value -18 instead of OPAL_SUCCESS
--------------------------------------------------------------------------
```
But we checked (see more information and discussion in the linked issue) that the MCA parameters were correctly set up in `CONDA_PREFIX/etc/openmpi-mca-params.conf` and got imported when MPI was initialized, so I had no idea why it complained. I could not reproduce this problem either. The current workaround I suggested was to set `OMPI_MCA_opal_cuda_support=0` manually prior to `mpirun`.

@jsquyres, any insight for how this could happen? 😇

cc: @mpmdean @mrakitin

**Comment by jsquyres** [comment]
I'm sorry, I totally missed the @metion on this issue until now 😨 

We usually find that these kinds of errors are when there's an unexpected place setting the MCA parameter value -- e.g., an unexpected config file or env variable set somewhere that wasn't expected.  If anyone still cares about this issue (because it's so old), it might be worth checking all possible locations where this value could have been set to ensure that it wasn't actually set.

**Comment by leofang** [comment]
Thanks, @jsquyres! One follow-up question:
> it might be worth checking all possible locations where this value could have been set to ensure that it wasn't actually set.

Do you have a list of such locations that Open MPI would look up documented somewhere?

**Comment by rajachan** [comment]
@leofang  this FAQ entry might help:
https://www.open-mpi.org/faq/?category=all#setting-mca-params

**Comment by leofang** [comment]
Great, thanks @rajachan!

**Comment by dalcinl** [comment]
@leofang I saw some of your comments in the linked issue, about using `reload()`. Yes, mpi4py.MPI will be imported twice, but a) Python imports are cached (`sys.modules`), and mpi4py is careful enough to not initialize MPI twice if the module init function is ever called more than once.

**Comment by leofang** [comment]
Thanks, @dalcinl! Apparently I forgot about a) and was not aware of b) 😅 Glad to know we have extra safe!
