### ISSUE TITLE
loosen run_exports to max_pin=x

### ISSUE THREAD

**Issue by isuruf** [conda-forge/openmpi-feedstock#74]
It has good major version compatibility. https://abi-laboratory.pro/?view=timeline&l=openmpi

**Comment by leofang** [comment]
@jsquyres Looks like Open MPI can guarantee ABI compatibility across minor versions?

**Comment by jsquyres** [comment]
Yes: https://github.com/open-mpi/ompi/blob/master/README.md#open-mpi-version-numbers-and-binary-compatibility

**Comment by leofang** [comment]
Thanks @isuruf for catching the issue and @jsquyres for the pointer 🙂
