### ISSUE TITLE
openmpi [linux]

### ISSUE THREAD

**Issue by dnadeau4** [conda-forge/openmpi-feedstock#8]
I see that your `meta.yaml` include `linux`, but I cannot find it in `conda-forge`.  Is there a way to build `openmpi` in `linux`

**Comment by dalcinl** [comment]
@minrk Do you have any idea what's going on? Linux builds simply do not get uploaded to the anaconda.org channel.

**Comment by minrk** [comment]
I think it's the `make check`. There's something in mpiexec that messes with the stdin pipe, causing the build script to terminate early, stopping before the upload command. https://github.com/conda-forge/conda-smithy/pull/337 should fix that, but hasn't been merged into conda-smithy.

**Comment by minrk** [comment]
(to be precise, not `make check` in particular, but apparently any invocation of `mpiexec` seems to cause this problem on circle.
