### ISSUE TITLE
Support for external openmpi libraries

### ISSUE THREAD

**Issue by heather999** [conda-forge/openmpi-feedstock#90]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I am a happy user of `conda install mpich=3=*_external` so I can utilize the mpich libraries available at NERSC (HPC).  I'd like to do the same with openmpi.  Looking at the [doc which mentions similar openmpi support is not yet available](https://conda-forge.org/docs/user/tipsandtricks.html#using-external-message-passing-interface-mpi-libraries), I'm wondering if things have improved with ABI compatibility so that this could be considered?

**Comment by dalcinl** [comment]
You should really ask upstream to Open MPI developers. Or you could try to implement the feature anyway and see whether it works. Without commitment from upstream, it is a risky move: who is going to take responsibility of the mess if the thing ever breaks?

**Comment by leofang** [comment]
If you open an issue upstream, please link it here so that we can follow, thanks 🙂

**Comment by beckermr** [comment]
Hi everyone. We should be fine to implement this. If it breaks, nobody is responsible. 

The Abi lab page for openmpi is pretty benign and we pin globally at 4 in conda forge anyways. 

https://abi-laboratory.pro/?view=timeline&l=openmpi

Cc @conda-forge/core for viz
